package runtime

import "errors"

var ErrSessionTerminal = errors.New("session is terminal")
var ErrSessionAwaitingApproval = errors.New("session is awaiting approval")
var ErrSessionBlocked = errors.New("session is blocked")
var ErrSessionApprovalGateTooLate = errors.New("session approval gate must be requested before execution starts")
var ErrNoPendingApproval = errors.New("session has no pending approval")
var ErrApprovalNotResolved = errors.New("approval is not ready to resume")
var ErrApprovalResumeContextMissing = errors.New("approval resume context no longer points to the original blocked execution")
var ErrBlockedRuntimeAlreadyActive = errors.New("session already has a blocked runtime")
var ErrBlockedRuntimeNotActive = errors.New("blocked runtime is not active")
var ErrBlockedRuntimeNotPending = errors.New("blocked runtime is not pending")
var ErrInvalidBlockedRuntimeRequest = errors.New("blocked runtime request is invalid")
var ErrInvalidBlockedRuntimeResponse = errors.New("blocked runtime response is invalid")
var ErrDirectActionInvokeUnsupported = errors.New("direct action invocation is unsupported; use the step runtime path")
var ErrPlanRevisionBudgetExceeded = errors.New("plan revision budget exceeded")
var ErrRuntimeBudgetExceeded = errors.New("total runtime budget exceeded")
var ErrStepRetryBudgetExceeded = errors.New("step retry budget exceeded")
var ErrStepBackoffActive = errors.New("step retry backoff active")
var ErrRuntimeHandleNotActive = errors.New("runtime handle is not active")
var ErrInteractiveControllerNotConfigured = errors.New("interactive controller is not configured")
var ErrInteractiveRuntimeNotFound = errors.New("interactive runtime is not found")
var ErrProgramDuplicateNodeID = errors.New("program contains duplicate node id")
var ErrProgramMissingNodeID = errors.New("program node id is required")
var ErrProgramDependencyNotFound = errors.New("program dependency references unknown node")
var ErrProgramEntryNodeNotFound = errors.New("program entry node references unknown node")
var ErrProgramCycleDetected = errors.New("program contains cyclic dependencies")
var ErrProgramMultiTargetUnsupported = errors.New("program multi-target execution is not supported yet")
var ErrProgramTargetDiscoveryUnsupported = errors.New("program target discovery is not supported yet")
var ErrProgramBindingDependencyMissing = errors.New("program binding step selector must reference an explicit dependency")
var ErrProgramOutputRefUnsupported = errors.New("program output-ref bindings are not supported yet")
var ErrProgramAttachmentUnsupported = errors.New("program attachment bindings are not supported yet")
var ErrProgramInputBindingUnsupported = errors.New("program input binding kind is not supported")
var ErrProgramBindingResolveFailed = errors.New("program input binding could not be resolved")
